Add --publish switch to boot and quick.  #21

diff --git a/libexec/commands/boot b/libexec/commands/boot
--- a/libexec/commands/boot
+++ b/libexec/commands/boot
@@ -12,11 +12,14 @@ help()
 Usage: ${WHOAMI} [ OPTIONS ] CONTAINER-NAME IMAGE-NAME
 
 Options:
-  --login    Log into the container after it has booted.  Implied
-               if $LOGIN_ON_BOOT is set to any non-empty value.
-  --no-login Don't log into the container after boot.  Overrides
-               $LOGIN_ON_BOOT if set.
-  --verbose  Print the Docker command used to start the container
+  --login            Log into the container after it has booted.  Implied
+                       if $LOGIN_ON_BOOT is set to any non-empty value.
+  --no-login         Don't log into the container after boot.  Overrides
+                       $LOGIN_ON_BOOT if set.
+  --publish P1[:P2]  Publish the container's port P2 on the host's port P1
+                       or P1 for both if P2 is not provided.  (Same syntax
+                       as used by Docker.)
+  --verbose          Print the Docker command used to start the container
 
 Example:  ${WHOAMI} --login thing el9
 EOF
@@ -25,6 +28,9 @@ EOF
 [ "${DDB_LOGIN_ON_BOOT}" ] \
     && LOGIN_AFTER=true \
 	|| LOGIN_AFTER=false
+
+PORTLIST="${TMPBASE}/ports"
+touch "${PORTLIST}"
 
 VERBOSE=false
 while echo "$1" | grep -E -qe '^--'
@@ -45,6 +51,11 @@ do
 	    shift
 	    ;;
 
+	--publish)
+	    echo "$2" >> "${PORTLIST}"
+	    shift 2
+	    ;;
+
 	--verbose)
 	    VERBOSE=true
 	    shift
@@ -55,6 +66,22 @@ do
 	    exit 1
     esac
 done
+
+
+# Validate the port list and generate options
+
+PORTOPTS=""
+while read PORTSPEC
+do
+    echo "${PORTSPEC}" | grep -E -q -e '^[1-9][0-9]*(:[1-9][0-9]*)?$' \
+	|| die "Invalid exposure '${PORTSPEC}'"
+    HOSTPORT=$(echo "${PORTSPEC}" | cut -d : -f 1)
+    CONTPORT=$(echo "${PORTSPEC}" | cut -d : -f 2)
+    [ "${HOSTPORT}" -le 65535 -a "${CONTPORT}" -le 65535 ] \
+	|| die "Invalid port in exposure '${PORTSPEC}'"
+    PORTOPTS="${PORTOPTS} -p ${PORTSPEC}"
+done < "${PORTLIST}"
+
 
 NAME="$1"
 CONTAINER_NAME="${DDB_CONTAINER_PREFIX}${NAME}"
@@ -120,6 +147,7 @@ do_docker $DOCKER run \
     --rm \
     ${PRIVILEGED} \
     ${VOLUME_CGROUP} \
+    ${PORTOPTS} \
     --volume "${USER_HOME}:${USER_HOME}" \
     --security-opt label:disable \
     "${IMAGE_FULL}:latest" \
